### ISSUE TITLE
Add copyrights/license information

### ISSUE THREAD

**Issue by vazhnov** [mgorny/python-guide#1]
Hello!

I found link to this project in https://blogs.gentoo.org/mgorny/2020/02/21/gentoo-python-guide/

Could you please add information about license — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license, probably from Creative Commons pool.

**Comment by mgorny** [comment]
Hope that's good enough for you.

**Comment by vazhnov** [comment]
Creative Commons Attribution 4.0 International — amazing!
@mgorny, thank you very much!
